

class CustomError(Exception):
    """ 自定义异常类 """
    pass
